name: Deploy Django project

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Python 3.8
        uses: actions/setup-python@v3.1.3
        with:
          python-version: "3.8"

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y python3-venv
          python -m venv venv
          source venv/bin/activate
          python -m pip install --upgrade pip
          pip install -r Watoon/requirements.txt
          python manage.py migrate

      - name: Generate deployment package
        run: zip -r deploy.zip Watoon -x 'Watoon/*.git*'

      - name: Get current time
        id: current-time
        run: echo "::set-output name=formattedTime::$(date -u +'%Y-%m-%dT%H:%M:%S')"

      - name: Deploy to EB
        uses: einaregilsson/beanstalk-deploy@v21
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          application_name: test  # EB 애플리케이션명
          environment_name: Test-env  # EB 환경명
          version_label: github-action-${{ steps.current-time.outputs.formattedTime }}
          region: ap-northeast-2
          deployment_package: deploy.zip
