
# name: Deploy Django project

# on:
#   push:
#     branches:
#       - main

# jobs:
#   build:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Checkout
#         uses: actions/checkout@v2

#       - name: Set up Python 3.8
#         uses: actions/setup-python@v3.1.3
#         with:
#           python-version: "3.8"

#       - name: Install dependencies & migration
#         run: |
#           sudo apt-get update
#           sudo apt-get install -y python3-venv zip
#           python -m venv venv
#           source venv/bin/activate
#           python -m pip install --upgrade pip
          
#           cd Watoon
#           pip install -r requirements.txt
          
#           python manage.py migrate

#       - name: Generate deployment package
#         run: zip -r deploy.zip . -x '*.git*'

#       - name: Get current time
#         uses: 1466587594/get-current-time@v2
#         id: current-time
#         with:
#           format: YYYY-MM-DDTHH-mm-ss
#           utcOffset: "+09:00"

#       - name: Deploy to EB
#         uses: einaregilsson/beanstalk-deploy@v21
#         with:
#           aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
#           aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
#           application_name: test  # EB 애플리케이션명
#           environment_name: Test-env  # EB 환경명
#           version_label: github-action-${{ steps.current-time.outputs.formattedTime }}
#           region: ap-northeast-2
#           deployment_package: deploy.zip
# ###
name: Deploy Django project

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Python 3.11
        uses: actions/setup-python@v3.1.3
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          cd Watoon
          python -m pip install --upgrade pip
          pip install -r requirements.txt  # 필요한 경우 requirements.txt 파일을 사용하세요.

      - name: Database migration
        run: |
          cd Watoon
          sudo python -m venv /var/app/venv/staging-LQM1lest
          source /var/app/venv/staging-LQM1lest/bin/activate
          python manage.py migrate
        
      - name: Generate deployment package
        run: zip -r deploy.zip . -x '*.git*'

      - name: Get current time
        uses: 1466587594/get-current-time@v2
        id: current-time
        with:
          format: YYYY-MM-DDTHH-mm-ss
          utcOffset: "+09:00"

      - name: Deploy to EB
        uses: einaregilsson/beanstalk-deploy@v21

        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          application_name: test #EB 애플리케이션명
          environment_name: Test-env #EB 환경명
          version_label: github-action-${{steps.current-time.outputs.formattedTime}}
          region: ap-northeast-2
          deployment_package: deploy.zip